# Generated by Django 5.0.7 on 2024-10-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSa', 'Nebulosa'), ('GALÁXIAS', 'Galáxias'), ('ESTRELAS', 'Estrelas'), ('PLANETAS', 'Planetas')], default='', max_length=100),
        ),
    ]
