# Generated by Django 5.0.7 on 2024-10-31 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_alter_fotografia_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotografia',
            options={'verbose_name_plural': 'Space photos'},
        ),
    ]
