# Generated by Django 5.0.7 on 2024-10-31 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_fotografia_data_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='foto',
            field=models.ImageField(upload_to='fotos/%Y/%m/%d'),
        ),
    ]
