# Generated by Django 5.0.7 on 2024-10-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_alter_fotografia_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'Nebulosa'), ('GALÁXIAS', 'Galáxias'), ('ESTRELAS', 'Estrelas'), ('PLANETAS', 'Planetas')], default='', max_length=100),
        ),
    ]
